language: node_js
node_js:
- 11.8.0
deploy:
  provider: heroku
  api_key:
    secure: JFsNVKErEiwctYCo73ZWXY0ejfS/3KnSUy2BOkst24pgqKUof+viIvvsAtsQsRGrhTHn9ChqpEA7Y5oLDLOQJqdumIIizEd6M+YJfBvvTghXQ3SsS2gkhIbFIY60WSI3uigXZaF8XuuGce3rd4LQwSAF85PsS5tMOf4z0BphRruiGVTBxeJ2B8uTWd/A36SvI7+vNp/jRxosIOVIzkv8mta5ZsRizi1xGRC0vAvRh1OG8KpA52hlcLF4nD5JDqmHUjJJmlf9nQsfzm2y0gfOb6/nUd5LoTgffTyRTi6zjB4wOdUvlzQyhDv2p4DnK8nO2P5Ah/GIW8DaB9v9OKiErDuiBM2lgpG2Q7L2VkkOja/dmoTPueKah02a6WoXhAyAJ4SaW9JyOxw1QmRRhxHiY8/ssmHN3GmS5IfUMF9KmAwf4OZDocELbAHVb2ve9b66tHNTsQRD3Fi9dCNj4bGoFgNxLJiObqy2XTY5iyh6lzivHUcmJZtnNd9uIQZ+NfBuAGjHHcV96DsgTeQ50/6qcTzOMuGv0+2XwRF8NtzqRPfwmr06ncK7C0yYcnJtw9zmqlCQUw8VBkpaTDvnGSqXsmbrhQt4dcdfJzb/FdG1O4Wj1iF7D8d4Ai/i/YXT1m10uJ53aPPYuu6KBjHBawK2H58d2Cyv3OnWXwg4jUfSYZ4=
